### ISSUE TITLE
Only shows the first 20 timelapse recordings

### ISSUE THREAD

**Issue by ZemaToxic** [bambulab/Bambu-Handy#10]
When checking timelapse footage in the android app it only shows the first 20 recordings and no subsequent ones, if you delete one of the first 20 and refresh it shows recording 21 as recording 20

**Comment by WanaGo** [comment]
Confirmed here also. Same deal, shows only 20. If you actually scroll down to the bottom the videos go blank and pops up saying "There's nothing here".

**Comment by pepsiliu** [comment]
Please add tickets via app, we need printer's logs to see what went wrong.

**Comment by WanaGo** [comment]
> Please add tickets via app, we need printer's logs to see what went wrong.

Unsure what this has to do with the printer or the printer logs. The timelapse videos are on the SD card correctly, its just the Bambu Handy app is only showing 20 videos in the App. If you delete 1 of the early videos, then one of the later ones will show up in the app, but still only show 20 total.
If you put the SD card into your PC, I can see over 30 videos, but the Handy app only displays 20

**Comment by pepsiliu** [comment]
> > Please add tickets via app, we need printer's logs to see what went wrong.
> 
> Unsure what this has to do with the printer or the printer logs. The timelapse videos are on the SD card correctly, its just the Bambu Handy app is only showing 20 videos in the App. If you delete 1 of the early videos, then one of the later ones will show up in the app, but still only show 20 total. If you put the SD card into your PC, I can see over 30 videos, but the Handy app only displays 20

Yes, the list of timelapse videos on the SD card is read from printer, which means something was wrong, when printer gave the infomation to Handy, so we need printer's log to analyse. We'll also do some tests at the same time.

**Comment by ZemaToxic** [comment]
> > > Please add tickets via app, we need printer's logs to see what went wrong.
> > 
> > 
> > Unsure what this has to do with the printer or the printer logs. The timelapse videos are on the SD card correctly, its just the Bambu Handy app is only showing 20 videos in the App. If you delete 1 of the early videos, then one of the later ones will show up in the app, but still only show 20 total. If you put the SD card into your PC, I can see over 30 videos, but the Handy app only displays 20
> 
> Yes, the list of timelapse videos on the SD card is read from printer, which means something was wrong, when printer gave the infomation to Handy, so we need printer's log to analyse. We'll also do some tests at the same time.

Uploaded a support ticket in the App as requested, Ticket No: US220929700000

**Comment by WanaGo** [comment]
I also updated the log via the App ticket as requested. Ticket No: US220929800000

**Comment by WanaGo** [comment]
> I also updated the log via the App ticket as requested. Ticket No: US220929800000

I just realised my SD card was not in the printer when I uploaded the log via the App. Does it need the SD card in the printer at the time of the log being sent, or does it not send anything off the SD card itself? If you need me to resend the log (new ticket) with the SD card in the printer, please let me know. I had it in my PC as I was looking at the files on there directly.

**Comment by pepsiliu** [comment]
> 

Thanks, SD card is not required.

**Comment by sodachen22** [comment]
> > I also updated the log via the App ticket as requested. Ticket No: US220929800000
> 
> I just realised my SD card was not in the printer when I uploaded the log via the App. Does it need the SD card in the printer at the time of the log being sent, or does it not send anything off the SD card itself? If you need me to resend the log (new ticket) with the SD card in the printer, please let me know. I had it in my PC as I was looking at the files on there directly.
Thanks for the LOG.
1. According to LOG, we found a software bug in the printer which led to Handy only displaying 20 videos. We will fix the problem in the future.
2. Studio uses another API, it is OK to display all timelapse videos.

**Comment by ZemaToxic** [comment]
Most recent app update fixed this, Issue is now resolved
