### ISSUE TITLE
video not working on ios 1.1.1

### ISSUE THREAD

**Issue by MrDaGree** [bambulab/Bambu-Handy#100]
video stream isnt working anymore. just says failed to connect

**Comment by pepsiliu** [comment]
How does it behave in the Studio?

And please provide the printer's model & firmware version.

**Comment by MrDaGree** [comment]
Bambu studio works perfectly. X1C is on 01.05.01.00

**Comment by LibaoBambu** [comment]
Please reopen if this issue shows up again.
