### ISSUE TITLE
[Bambu Studio Not loading on windows 11] Bambu Studio Not Loading Windows 11

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/Bambu-Handy#106]
I have tried updating vcred to newest version, installing legacy media player support, uninstalling the software.  It does not load to main page and just freezes

**Comment by LibaoBambu** [comment]
Have nothing to do with Bambu Handy. Please visit [https://github.com/bambulab/BambuStudio/issues](https://github.com/bambulab/BambuStudio/issues) to post your request.
And I also had transmitted this tickets to Studio team internally.
Thanks!
