### ISSUE TITLE
Live view

### ISSUE THREAD

**Issue by chuckkay** [bambulab/Bambu-Handy#107]
Love the addition of temp, % completion and status information added to Landscape live preview video, but i see no reason why current layer and time remaining can not be included..  see attached screenshots.. additionally a toggle option should be added to turn on/off these pieces of print information from the live view..
![IMG_4414](https://github.com/bambulab/Bambu-Handy/assets/10617746/b65f12c8-960c-4ce8-961f-bee1ab93efff)
![IMG_4415](https://github.com/bambulab/Bambu-Handy/assets/10617746/0aefa43f-8336-4e74-a75e-a15e30dd1e39)

**Comment by LibaoBambu** [comment]
Please reopen if there are any other requests.
