### ISSUE TITLE
[Issue] Bambu Handy Android App not updating tickets

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/Bambu-Handy#108]
I've recently noticed that my app isn't showing my updated support ticket information. i have to use my email app to respond to support.

**Comment by LibaoBambu** [comment]
Thanks for opening an issue!
Could you please describe the issue you are having?
Thanks!

**Comment by 3D-Pink-Girl** [comment]
> Thanks for opening an issue! Could you please describe the issue you are having? Thanks!

My support tickets aren't updating in the app. I've done clear cache and data and now uninstall/install. Still isn't showing latest updates that support have left. Any ideas?

**Comment by 3D-Pink-Girl** [comment]
Bambu Handy android app version 1.1.2

Previously it had no issues regarding the support tickets but ever since update it’s not showing new messages.

**Comment by LibaoBambu** [comment]
[image]
Long press to provide your ticket number, I'll follow up on this issue.

**Comment by LibaoBambu** [comment]
@3D-Pink-Girl  send ticket number to libao.jia@bambulab.com with email

**Comment by 3D-Pink-Girl** [comment]
I see that your version 1.2.0 actually fixed this issue in bug fixes

"Fixed the issue that some devices did not display ticket responses."

**Comment by 3D-Pink-Girl** [comment]
> @3D-Pink-Girl send ticket number to [libao.jia@bambulab.com](mailto:libao.jia@bambulab.com) with email

Yeah I've been responding to support by email as the app isn't updating the responses. I'll try 1.2.0 and let you know. Thanks again for your help

**Comment by LibaoBambu** [comment]
The new version will be released tomorrow, and I hope it can solve your problem. If you have any tasks, please let me know. Thank you for your feedback.

**Comment by 3D-Pink-Girl** [comment]
> The new version will be released tomorrow, and I hope it can solve your problem. If you have any tasks, please let me know. Thank you for your feedback.

Oh that's awesome news. Thank you so much. I will report back on the results once I've updated to 1.2.0. Big thanks to you and the team here 🥇 😘 You're doing fab work

**Comment by 3D-Pink-Girl** [comment]
Hi, I still don't see the update yet 1.2.0. Are you still working on that build? Thanks x

**Comment by 3D-Pink-Girl** [comment]
I can't find the 1.2.0 update anywhere 😕

**Comment by LibaoBambu** [comment]
please try again.   [image]

**Comment by 3D-Pink-Girl** [comment]
It came up this time lol. Thank you so much 😘
