### ISSUE TITLE
Machine Assistant - Bambu Handy Android

### ISSUE THREAD

**Issue by WanaGo** [bambulab/Bambu-Handy#11]
I have an error showing in the Machine Assistant (0c0003000002000c), however when you click on it, it goes to a website which does not have any results.
The error specifics I am not worried about right now as I know what it is, but you cannot clear the error either, it stays up, and it partially covers the camera box on the home screen also.
I have already cleared it on the printer, but it remains in the Handy app.

**Comment by pepsiliu** [comment]
The HMS messages from the printer only dismiss (in fact) after users fixed these warnings/errors on the printer.
To compact with multi app, we won't support a real [ignore] button for the HMS in the short term.
