### ISSUE TITLE
[Issue] Important notifications not working-

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/Bambu-Handy#112]
Neither on IOS nor on Android, although all notifications are allowed, will important notifications like "filament runout", "can't pull out filament" etc. not get displayed. 
Only notifications like "print cancelled" or "print finished" will get displayed.

**Comment by drewzh** [comment]
Just adding my experience. Also experiencing the same issue on iOS. Notifications are enabled but do not work. I haven't had a single notification since getting the printer a few days ago.

**Comment by psts** [comment]
Not working for me either. I got notifications for half a day some days ago and then back to not getting any. 
Have tried uninstalling and reinstalling the app.

**Comment by psts** [comment]
I think I have figured out when it works and when it doesn't.

If you send a job from Bambu Studio, I get notifications.
If I start the job from the cache on the printer, I don't get notifications.

**Comment by LibaoBambu** [comment]
@psts Because start the job from the cache on the printer does not go through our cloud service.
