### ISSUE TITLE
[Issue] & symbol breaks 3mf saves.

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/Bambu-Handy#113]
Problem: Any time you use the & symbol with the built in text shape maker and save the file you will get the error "The file does not contain any geometry data" when reopening the file.

**Comment by Notarin** [comment]
This is not the repo for Bambustudio, this is the repo for the mobile Android/IOS app, Bambu-Handy

**Comment by LibaoBambu** [comment]
Please visit https://github.com/bambulab/BambuStudio/issues to post your request.
I also had transmitted this tickets to Studio team internally.
Thanks!
