### ISSUE TITLE
Speed on app doesn't match current printer speed 

### ISSUE THREAD

**Issue by Draakul69** [bambulab/Bambu-Handy#13]
On the app the print speed shows as 100% or standard but when I check the speed from the touchpad on the printer it is what I had it assigned to beforehand and doesn't always match what the app says. Same with Bambu studio.

**Comment by pepsiliu** [comment]
I have tested on handy(1.0.5) and printer(01.01.00.03), and I could get right speed both on handy and printer. Can u provide ur versions?

**Comment by Draakul69** [comment]
Updating the app corrected the issue.
