### ISSUE TITLE
Feature request: Add the RH humidity data for the AMS as shown in the app screenshot

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/Bambu-Handy#14]
It would be super handy for people to get an idea of whether they need to refresh their AMS desiccant if the RH was shown in the app, as was advertised as a feature:

![image](https://user-images.githubusercontent.com/63362209/195104064-1bc27a24-03fd-45f8-ae0c-341b568e7daa.png)

**Comment by pepsiliu** [comment]
Supported on release version 1.0.6
