### ISSUE TITLE
Support Tickets do not show on Bambu Handy

### ISSUE THREAD

**Issue by jltendler** [bambulab/Bambu-Handy#144]
Support ticket counts render and display as 0 in bambu handy, but I have a support ticket visible on the website.

**Comment by jltendler** [comment]
Screenshots on the forum post here: https://forum.bambulab.com/t/bambu-handy-doesnt-show-support-tickets-in-app/33641

**Comment by beibaochufa** [comment]
Do you still have this problem now?

**Comment by jltendler** [comment]
Yes:
![image](https://github.com/bambulab/Bambu-Handy/assets/6431001/7d8f9d78-ab06-4846-8fbd-28cb0137d191)
![image](https://github.com/bambulab/Bambu-Handy/assets/6431001/fca71385-3170-4227-a636-26c2fdf4e5da)

App version 2.2.0

**Comment by beibaochufa** [comment]
After our analysis, your Ticket is a MakerWorld Ticket, and you need to see it in the "MakerWorld Tickets" in the APP. Please find the following entrance to see if there is your ticket.
In addition, we will synchronize the double-ended description to make it clearer. Thank you for your feedback.
![img_v3_025j_5fe26a3f-52c9-4c34-84b8-a7607027b49g](https://github.com/bambulab/Bambu-Handy/assets/18466882/6206a103-c0c1-4e0a-becf-7248c0f073a3)
