### ISSUE TITLE
Missing AMS jam notification translation

### ISSUE THREAD

**Issue by IoTMOD** [bambulab/Bambu-Handy#165]
There is no German translation for an AMS filament jam.
The app uses the system language (German).

Actual behavior: Chinese notification

Expected behavior: German or at least English notification if the German translation is not available.

![Screenshot_20240105-185055~2.png](https://github.com/bambulab/Bambu-Handy/assets/34713374/2bd6e20c-507b-4a60-a379-6645f4731b22)

**Comment by LibaoBambu** [comment]
Cloud interface has been fixed, thanks for your report. Reset your app will load new translation.

**Comment by IoTMOD** [comment]
I was able to test it, working as expected now. Thanks!
