### ISSUE TITLE
Stopping one print on bed

### ISSUE THREAD

**Issue by Lcharsh** [bambulab/Bambu-Handy#17]
Octoprint has a feature that if one of the models is failing you can stop just that model and finish the other ones on the bed. I have gone through most of a roll of filament because of this. The one model is fine but other fails.  If I could stop just that model it would save on waste.

**Comment by pepsiliu** [comment]
The handy and printer both support this feature. Users can enable it on device main page's top-right menu --> Print Options. See the screenshot for details.
![Simulator Screen Shot - iPhone 14 Pro - 2022-10-18 at 09 36 42](https://user-images.githubusercontent.com/112543500/196314969-1c3b030e-40ba-4098-a1a6-651e3bc0e2db.png)

**Comment by pepsiliu** [comment]
The feature is in alpha testing.

**Comment by LibaoBambu** [comment]
Feature has been supported.
