### ISSUE TITLE
"filament has run out" notification does not clear from Bambu Handy

### ISSUE THREAD

**Issue by ElJeffe** [bambulab/Bambu-Handy#174]
2 days ago, I got [this](https://wiki.bambulab.com/en/x1/troubleshooting/hmscode/0700_2000_0003_0002) notification on my app because the AMS switched filaments. I can however no clear the notification. It stays visible on the screen and in the Machine Assistant page of the Settings. There seem to be no way to confirm or clear the notification.
P1S version: 01.05.02.00
AMS: 00.00.06.40
BambuHandy (Android): 2.6.1

![Screenshot_2024-02-08-10-04-39-07_65ccff193caf2ecf022bf931f3b12b60](https://github.com/bambulab/Bambu-Handy/assets/54236/40ebee74-9e19-4561-9a01-cdcce4388144)
![Screenshot_2024-02-08-09-59-50-95_65ccff193caf2ecf022bf931f3b12b60](https://github.com/bambulab/Bambu-Handy/assets/54236/86028ccf-ec91-4454-b696-7c02d2b5f1d4)

**Comment by LibaoBambu** [comment]
Message should clear when Slot2 load a new filament. For the current firmware version you need to restart the printer to clear this hms message and firmware will fix this issue in the next version.

**Comment by RozeDoyanawa** [comment]
I have the same issue with my recently purchased P1S (firmware is the latest public)
HMS_0700_2000_0003_0002 is stuck and does not clear. It gets "replaced" when another slot runs out. But it does not clear.

**Comment by M450NC** [comment]
Same issue here. AMS just purchased for P1S. Slot1 and Slot3 both ran out and this error persisted for ages. Had to reboot my printer at the plug 3 or 4 times to get the errors to go.

**Comment by cyberhuman** [comment]
Why is this issue closed?
The notification persists on my X1E.

**Comment by LibaoBambu** [comment]
> 为什么这个问题关闭了？ 我的 X1E 上仍然存在通知。

Please create a ticket to provide more info [https://bambulab.com/en-eu/my/support/tickets](url), Thanks.

**Comment by bsaunder** [comment]
I'm having the same problem with my X1C on the latest firmware.

@LibaoBambu what firmware version allegedly resolved this issue?

**Comment by DapperDangus** [comment]
@LibaoBambu same issue here. The notification cannot be dismissed until you reboot the printer.

**Comment by houmark** [comment]
Same for me on latest May release 01.08.00.00 (20240507) firmware.

**Comment by sodachen22** [comment]
I am sorry that the firmware with this fix is still in testing.

**Comment by angusmaul** [comment]
Still not fixed, sooo annoying.

**Comment by HDC67** [comment]
Still not fixed. I ran into this today with an up to date firmware on a brand new printer.

There have been at least 3 firmware releases since the ticket was closed.

**Comment by joethepeacock** [comment]
Still not fixed here - X1C

**Comment by phillipse01** [comment]
@LibaoBambu this issue is still occurring - I have it on my a1 newest firmware today

**Comment by RayBomb87** [comment]
Issue is still here x1c

**Comment by TGS78** [comment]
So when will this be finally fixed?

**Comment by bartoszpasiecznik** [comment]
P1S on latest firmware - Still not fixed, got the notification on Bambu Handy, P1S and Bambu Studio

**Comment by thePunderWoman** [comment]
X1C on latest firmware - I have this issue right now. I added new filament to the slot, and the message persists on the app. No way to clear it.

**Comment by TGS78** [comment]
> X1C on latest firmware - I have this issue right now. I added new filament to the slot, and the message persists on the app. No way to clear it.

actually you can only get rid of the notification by power cycling the printer.

**Comment by adamurban** [comment]
Can we get this reopened? (Or make a new bug?)

i am still having the same issue on my X1C with the latest FW, even though I see this reported as fixed back in Feb?

@LibaoBambu can you confirm which firmware version this is resolved with? I am running 01.08.02.00 at the moment.

**Comment by GittyUpSam** [comment]
Still not fixed on my X1C with latest firmware. Any error messages persist and are unclearable unless I power cycle the printer. Not a huge issue, but an annoyance.

**Comment by CodyPrince** [comment]
19 months later and this is still a problem. Why did they close this issue? maybe they can't fix it.

**Comment by RayBomb87** [comment]
Statistically looks better?
