### ISSUE TITLE
Fan speed discrepancy

### ISSUE THREAD

**Issue by GuzziRaz** [bambulab/Bambu-Handy#176]
There seem to be a slightly different formula/rounding error for main screen fan percentage, and fan control window figures. If I set it to 60% in the filament profile, the main printer screen of Bambu Handy says 50%:

![IMG_6502](https://github.com/bambulab/Bambu-Handy/assets/143495653/1fd54cad-9945-4677-a1c2-d935992b8687)

However, if you click on the fans to control them, it says 60% (nothing changed, but different speed shown):
![IMG_6501](https://github.com/bambulab/Bambu-Handy/assets/143495653/33b68fb8-b3d9-4566-88e6-1a94c8359ee7)

It shows correct in Bambu Studio:
![Screenshot 2024-03-01 at 02 21 22](https://github.com/bambulab/Bambu-Handy/assets/143495653/9d75be4b-1123-4d16-a685-054d4d2a6bfe)

**Comment by LibaoBambu** [comment]
Thank you for your feedback. And we will fix this issue in next version.
