### ISSUE TITLE
Request: Support full length filenames in history

### ISSUE THREAD

**Issue by lotsahelp** [bambulab/Bambu-Handy#182]
Most of our filenames are too long for the history pages. Please support showing the full filename somewhere in the history pages as they have key details that help finding the right file. Even if you can't put it in the listing, maybe put it in the details after tapping on an entry.

Thank you,

**Comment by LibaoBambu** [comment]
This feature has been recorded. We will process it as soon as other high-priority tasks are finished. Thanks for the feedback.
