### ISSUE TITLE
Request: Staging a file to history

### ISSUE THREAD

**Issue by lotsahelp** [bambulab/Bambu-Handy#183]
There are times prints are running and I'd like to go ahead and upload the next print into history for easy printing from the app. This would allow me to get everything ready in Studio and a staff member to just print from the app the next time a printer becomes available. 

Thank you,

**Comment by pepsiliu** [comment]
You can send a sliced task to the printer from the Studio. And start it via [Device Page]-[Settings (at thr ight top)]-[SD card]-[Models] by the Handy.

**Comment by lotsahelp** [comment]
@pepsiliu I don't want to send it straight to a printer, as it would only be available on that printer. I want to send it straight to Handy's history so I can print it on the next available printer. Please reopen.

**Comment by pepsiliu** [comment]
> @pepsiliu I don't want to send it straight to a printer, as it would only be available on that printer. I want to send it straight to Handy's history so I can print it on the next available printer. Please reopen.

Hi, I suggest you upload your printings to the makerworld. This will meet your needs.

**Comment by lotsahelp** [comment]
@pepsiliu How will that meet my needs for a private print farm?

**Comment by pepsiliu** [comment]
@lotsahelp Hi, the Makerworld supports uploading private 3mf.  
For farm printing, there desn't have any better support, but upload to the history is definitely not a good solution.
Please describe in detail your needs and the solution you expect, and we will discuss it and put it into the feature-list.
Please open this issue if you think it is necessary. Thank you again.
