### ISSUE TITLE
can not access sd card in handy 

### ISSUE THREAD

**Issue by scbizu** [bambulab/Bambu-Handy#196]
## Bambu Handy Version 

1.13.0

## Device Version

device: A1 mini Carbon CN 

firmware version: 01.02.00.00

AMS Lite version: 00.00.07.92

## Detail

much more like https://github.com/bambulab/BambuStudio/issues/3457

**Comment by LibaoBambu** [comment]
The A1 series does not currently support accessing timelapse videos from app.
