### ISSUE TITLE
Calibrating the micor lidar (sic)

### ISSUE THREAD

**Issue by yegct** [bambulab/Bambu-Handy#198]
During the Calibration step, the Calibration Flow checkboxes include:

- Cleaning nozzle tip
- Homing toolhead
- Calibrating the micor lidar

I expect it to say "micro lidar" instead of "micor lidar":
- Cleaning nozzle tip
- Homing toolhead
- Calibrating the micro lidar

**Comment by LibaoBambu** [comment]
Thank you for your feedback. Will be fixed in the next version.

**Comment by LibaoBambu** [comment]
version 2.11.0 has fixed this issue, thanks
