### ISSUE TITLE
Nozzle Temperature Problem

### ISSUE THREAD

**Issue by SaltWei** [bambulab/Bambu-Handy#203]
See https://github.com/bambulab/BambuStudio/issues/4467

**Comment by LibaoBambu** [comment]
Please refer to the wiki for problem-solving: [https://bambulab.com/en-eu/my/support/tickets](https://wiki.bambulab.com/en/x1/troubleshooting/cutter-stuck). If you need more professional guidance, please create a ticket https://bambulab.com/en-eu/my/support/tickets
