### ISSUE TITLE
Bambu Handy shows just ? for the AMS Slots

### ISSUE THREAD

**Issue by wtfteddy** [bambulab/Bambu-Handy#215]
![Screenshot_20240910-153002](https://github.com/user-attachments/assets/4a12ff91-40e1-4bbd-9a4d-399c8808d533)
I try Reinstall the App and restart the Printer.

**Comment by LibaoBambu** [comment]
Fixed, Some cloud services encounter an fatal issue [https://status.bambulab.com/incidents/l2gm98y38w5k](url). Thanks for the feedback.
