### ISSUE TITLE
[Feature Request] Allow zooming with the camera during print

### ISSUE THREAD

**Issue by TheCableGuy99** [bambulab/Bambu-Handy#22]
Can I request a feature to allow us to pinch zoom in with the camera while printing? Not just zooming into the center but to be able to target specific areas?

**Comment by KD7LRJ** [comment]
Not that we expect the camera to zoom optically, just that phone screens are small and we want to enlarge the available image to see something slightly better and be able to pan around to see other areas.

**Comment by pepsiliu** [comment]
It'll be supported on next released version.

**Comment by mainmind83** [comment]
It's working in in last version

**Comment by TheCableGuy99** [comment]
great!
