### ISSUE TITLE
[Issue] app needs hard restart video starting

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/Bambu-Handy#28]
when i open the app to view my print the video opens ok but when i go out the app and back in the video wont load and i need to close the app completely before it works

**Comment by pepsiliu** [comment]
> when i open the app to view my print the video opens ok but when i go out the app and back in the video wont load and i need to close the app completely before it works

Handy (1.0.5) already have this capability. Whenever user change pages or apps it'll reconnect  the video.
Or you can provider more information about this issue.

**Comment by pepsiliu** [comment]
Close it, since there is no more informations.
You can reopen it if this issue occurs again.
