### ISSUE TITLE
[Feature Request] sort timelapse videos with newest at top

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/Bambu-Handy#33]
put newest timelapse videos at the top, not the bottom of the list. i have hundreds of them and it is not fun to scroll all the way to the bottom to find my most recent ones.

**Comment by dereknheiley** [comment]
This

**Comment by sickerin** [comment]
Up voting this

**Comment by LibaoBambu** [comment]
It depends on the firmware, please reopen if this issue shows up again.
