### ISSUE TITLE
[UI bugs, minor, Android] Spelling/Grammar issues

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/Bambu-Handy#4]
When picking a profile picture, a spelling mistake:
![IMG_20220908_133922](https://user-images.githubusercontent.com/63362209/189131690-c098193a-3acd-44c0-92ab-b44db0b8a1cc.jpg)

A missing space when going to close an account:
![IMG_20220908_133820](https://user-images.githubusercontent.com/63362209/189131755-5eaf815c-f9fe-45ab-880d-f2e9c1b2ef3d.jpg)

When a printer is idle. This should probably say something like "No task is being performed on this device", if it changes when a calibration is being performed, or "No print is in progress on this device" if it only changes when something is being printed.
![IMG_20220908_133802](https://user-images.githubusercontent.com/63362209/189131764-83913bbc-9ab5-4d4e-9079-8cfb36281dc1.jpg)

**Comment by LibaoBambu** [comment]
thanks a lot for all of your comments and suggestions here. the new version app been submitted for app store to review.

**Comment by RobinWhitfield** [comment]
On the latest version both the idle message and spelling mistake have been corrected, but although the account cancellation page has a space, it also not has some additional brackets

![Screenshot_2022-09-10-16-04-18-15_65ccff193caf2ecf022bf931f3b12b60](https://user-images.githubusercontent.com/63362209/189489392-0f7d612b-e45e-497a-92a4-4710f42a0cb5.jpg)
