### ISSUE TITLE
Show filament and bed temp on history > prepare

### ISSUE THREAD

**Issue by dereknheiley** [bambulab/Bambu-Handy#43]
I had to start and cancel a print to find out if I needed to put in the cold or hot build plate for a PLA print. Please add both temps and max volumetric flow to this screen so I know what I can load in my printer if I want to reprint something from the history in the iOS app.

![8332213A-4B09-4AA9-8DF0-6C7F45C3554B](https://user-images.githubusercontent.com/3382160/206354117-93309fa2-4553-4c14-8b71-b99308db4bac.jpeg)

**Comment by LibaoBambu** [comment]
start print task will support choose hot bed, on next release version.

**Comment by LibaoBambu** [comment]
Feature has been supported.
