### ISSUE TITLE
Humidity readout too small unreadable

### ISSUE THREAD

**Issue by Printman76** [bambulab/Bambu-Handy#44]
1) The humidity readout is way too small and unreadable on even a large phone (I have a one plus 8 pro)

2) The readout should be a percentage not a fill meter
![AMS humidity suggestion](https://user-images.githubusercontent.com/103388419/207920056-260d88d5-bb2b-484c-b802-f380405b248a.png)

3) readout does not match the slicer
![Humidity doesnt match](https://user-images.githubusercontent.com/103388419/207920119-89e81e2f-63f9-44ce-a00e-ff43c11d6558.png)

**Comment by darkorb** [comment]
The humidity isn't percentage based, so the icon only changes color based on a few preset targets. The reasons are outlined in the release notes (and the data in the MQTT stream reflects this being like 0,1,2 etc. now and not 0-100).

**Comment by pepsiliu** [comment]
Good suggestion. It will be optimized in the next version.

**Comment by pepsiliu** [comment]
Updated on 1.0.14
