### ISSUE TITLE
[Feature Request] Printing Progress with Live Activities on iOS 16.1+ 

### ISSUE THREAD

**Issue by Jakubnim** [bambulab/Bambu-Handy#46]
Hello, 

Is there any way that Bambu iOS developers implement Live Activities for iOS 16.1 and up devices + iPhone 14 Pro Dynamic island version? Would be nice to check from time to time progress on my iPhone without unlocking it, just a quick glance. 

![17F9C795-EAEC-4715-80D8-DE82A9CA0728](https://user-images.githubusercontent.com/65075421/208225337-ca5bfe81-dae0-44d9-a03a-bbc63de433a7.png)

here’s developer note from Apple how to implement that with short description: 

https://developer.apple.com/design/human-interface-guidelines/components/system-experiences/live-activities

It would be awesome addition, I use it with tracking and taxi apps, would be great to have it in Handy also.

**Comment by Jakubnim** [comment]
Here’s more technical specification with activity kit which should enable Live tracking for print progress.

**Comment by Sir-Gavin** [comment]
I think this would by HANDY 🤪

**Comment by pepsiliu** [comment]
Duplicated with #36
