### ISSUE TITLE
[issue] no ios notifications

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/Bambu-Handy#49]
Ok I’m confused.  My handy app doesn’t give any notifications on my iPhone.  I have it set correctly in iPhone notifications and everything.  Anyone else having this issue or know how to resolve?  Tried firmware updates, app updates, removing app and reinstalling - still no print notifications….  i either have to keep opening and chrcking the app to see progress / status or look on printer

**Comment by pepsiliu** [comment]
Please provide more information, such as account email, printer dev_id. It would be more helpful if you add a ticket to give us the printer's logs.

**Comment by Snortimer** [comment]
I'm having the same problem. It was giving me notifications up until a couple weeks ago.

**Comment by LibaoBambu** [comment]
Please reopen if this issue shows up again.
