### ISSUE TITLE
iOS Dark mode

### ISSUE THREAD

**Issue by dereknheiley** [bambulab/Bambu-Handy#5]
iOS handy app should support native dark mode (os setting) or manual mode, including the loading screen, for example like Google chrome

![E0754571-C033-422C-B231-2CFE84626144](https://user-images.githubusercontent.com/3382160/189266392-637bcb03-d279-48fd-8a6f-73494c928ad5.jpeg)
![6DF20881-4748-4D8F-883A-D1A0ADCFFF09](https://user-images.githubusercontent.com/3382160/189266394-56ec03b5-5cc1-4070-a2f4-bcf70eeafed2.jpeg)
![3F0E1A37-DEB4-4544-9092-3198AEE2877F](https://user-images.githubusercontent.com/3382160/189266395-8fd5eecf-8fd1-47b4-9a3c-a96e382cf533.jpeg)
![2CDFA7AD-B4BB-4317-9113-BB2F394F15AB](https://user-images.githubusercontent.com/3382160/189266396-11933ce9-3033-4f5e-bd66-e0795322b2e4.jpeg)

**Comment by JustinRudebaugh** [comment]
100% agreed!

**Comment by DoubleTts** [comment]
yes, please

**Comment by MrDaGree** [comment]
+1 would love to have this feature! Theres been times especially at night where im not excited about blinding myself while checking on a print

**Comment by pepsiliu** [comment]
Released on 1.1.0
