### ISSUE TITLE
[Feature Request:
Full height prime / purge tower] Full height prime / purge tower

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/Bambu-Handy#50]
Add a tick box so it is possible to have a prime / purge tall produce to the same height as the model. 
The reason behind this is I have noticed when printing with Silk PLA there is a colour difference once the prime / purge tower has reached its required height. Currently, I have to add an additional model of the same height to resolve the issue. 

I can provide images of the issues if required?

**Comment by pepsiliu** [comment]
I think it's a feature for Bambu Studio?

**Comment by lanewei120** [comment]
@BambuLabDiscord
to better trace this issue, could you create this issue under https://github.com/bambulab/BambuStudio?

thanks

**Comment by pepsiliu** [comment]
View  [https://github.com/bambulab/BambuStudio](BambuStudio)
