### ISSUE TITLE
[and can you please add raft air gap to your bambu slicer please and thank you] raft air gap

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/Bambu-Handy#53]
Separation Distance – This is an important setting that defines the height of the air gap between the raft and your part. Typically, having a gap of at least 0.1mm will help keep the part connected to the raft, while still allowing for easy separation once the print is complete.

The Raft Air Gap setting is simply how large the gap is between the raft and the model itself. The larger this gap is, the easier it is to remove. It basically

**Comment by lanewei120** [comment]
@BambuLabDiscord 
to better trace this issue, could you create this issue under https://github.com/bambulab/BambuStudio?

thanks

**Comment by pepsiliu** [comment]
View  [https://github.com/bambulab/BambuStudio](BambuStudio)
