### ISSUE TITLE
[issue] No video from p1p in handy app

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/Bambu-Handy#54]
after installing the camera in the p1p the bambu handy app shows “Connect failed” using the latest version of the iOS app and latest firmware on the printer.

**Comment by pepsiliu** [comment]
Please add a ticket to us, we need logs from P1P.  After that you can reset the P1P as a temporary solution.

**Comment by CCS86** [comment]
I just started a support ticket (US230117658001) for the same issue with my X1C.

Live video feed has been working perfectly in Handy until today. It still works fine in studio. Handy can issue commands to the printer, but not view video or browse media.

**Comment by RyanEwen** [comment]
Try removing the printer from your account and then pairing it again. It won't lose any settings or its name. Had to do this for both of my P1Ps to get video to work after installing the cameras.

**Comment by LibaoBambu** [comment]
Please reopen if this issue shows up again.
