### ISSUE TITLE
Application doesn't send notifications on error/warnings

### ISSUE THREAD

**Issue by msoffen** [bambulab/Bambu-Handy#55]
When there is a problem with something, The Handy App doesn't give a notification.  If I log into the app, it shows me - but if I'm not constantly looking at the application, it could be an hour+ before I see an issue that takes 30 seconds to fix.

**Comment by pepsiliu** [comment]
Let me confirm some informations. 
Do you mean the notification from phone system or the message from Handy App? 
And alse please provide the following information:
1. Phone system: iOS/Android
2. Handy version:
3. Printer model:
4. Printer version:

**Comment by Guilouz** [comment]
@pepsiliu Same issue for me oniOs device, app doesn't send push notifications on errors.

Phone system: iOS
Handy version: Latest on Apple Store
Printer model: X1C
Printer version: Latest firmware

**Comment by pepsiliu** [comment]
We suggest u add a ticket about this kind of issue, we also need more logs from the printers.

**Comment by screech24** [comment]
Same issue for me using latest p1p firmware 01.04.01.00 on both ios and android.

**Comment by LibaoBambu** [comment]
Please reopen if this issue shows up again.
