### ISSUE TITLE
Lamp state is not accurate in Handy (P1P)

### ISSUE THREAD

**Issue by smford** [bambulab/Bambu-Handy#58]
When the lamp is turned on when a job is printed from a computer, the status of the lamp does not get updated in Handy.

This will mean that the lamp will be on, but the handy app will say it is off.

**Comment by pepsiliu** [comment]
Duplicated with #57

**Comment by smford** [comment]
> Duplicated with #57

They appear very different from a user perspective.

#57 is about the P1P not turning off the lamp upon job completion - this could be in the gcode, or a setting in the P1P to timeout the lamp

whilst #58 is about changes in state to the lamp not being pushed to clients - or alternatively clients polling for the state of the lamp.

**Comment by pepsiliu** [comment]
Yes, I have make a double check on the #57, It'll be transferred to P1P guys.

**Comment by pepsiliu** [comment]
Fixed on P1P U1 hotfix. Will be released soon.
