### ISSUE TITLE
New Feature: View/Start Jobs Stored on Printer

### ISSUE THREAD

**Issue by Pahlsjt** [bambulab/Bambu-Handy#60]
You can send files to printer’s SD card using Bambu slicer. Only want to start job is to use the HMI on the printer or use slicer. I would like to be able to start jobs stored on the machine using the Handy app.

**Comment by broncosis** [comment]
yes please this is something I would very much want

**Comment by ab3dgeek** [comment]
yes pls, would be nice.

**Comment by LibaoBambu** [comment]
Feature has been supported.
