### ISSUE TITLE
Landscape video stream stats

### ISSUE THREAD

**Issue by RadTechDad** [bambulab/Bambu-Handy#64]
I love watching my printer work while my phone is in landscape mode because i can see the image clearer. However, I'd also like to be able to know the stats (temps, % completion) without have to exit out of landscape.

Would it be possible to have an "overlay" with this info over the video while in landscape mode? Maybe even a collapsable overlay box.

Thanks

**Comment by pepsiliu** [comment]
Supported above 1.1.0.
