### ISSUE TITLE
Bug - cant clear spaghetti detected message from app

### ISSUE THREAD

**Issue by chuckkay** [bambulab/Bambu-Handy#68]
I got a long print (20hours), printer sent a message “spaghetti detected” So i cleared it at the printer, but now the message wont go away on the app, since then i got a warning about a backed up poop chite cleared it and the message went away, but the spaghetti message still remains on handy app on the main screen overlayed on to of the live video.and a red dot and on setting “Machine assistanant” with a red  (1) badge

**Comment by sodachen22** [comment]
@chuckkay Did the printing paused when "spaghetti detected" message is displayed? There are two types of spaghetti detection result according to the confidence of AI, one is warning, another is error. When the result is error type, the printing job will be paused, and the user need to click "resume" on Handy/Studio/Screen to resume the printing job. When the result is warning type, there is only a warning message. When warning message is display, it will not be cleared until the starting of the next printing job. After a short internal discussion, we will optimize the behavior of the warning message to make it follow the latest spaghetti detection result. Thank you for the reporting.
