### ISSUE TITLE
[Feature Request] - Mark a warning as read

### ISSUE THREAD

**Issue by fourtwizzy** [bambulab/Bambu-Handy#73]
I am using the latest iOS version of Bambu Handy. I'd like to put in a feature request to mark a warning / error as read. As an example I printed something on textured PEI which at current isn't supported with first layer inspection. That is perfectly acceptable, but once you hit layer two it doesn't matter anyway. Being able to mark the warning as read or dismiss it would be nice. Instead for the remainder of the print there is a warning banner from the live camera view. There is a red notification dot on the same page. That takes you to the next window with a red mark all to get to the warning that you have to accept if you are using textured PEI at the moment anyway. 

So I thought if it could be dismissed or at least marked as read there isn't a notification or warning banner for the whole print. Photos below.

![image](https://user-images.githubusercontent.com/1735941/222610779-73d99095-fc2c-4464-9854-f9c11c110512.jpeg)

![image](https://user-images.githubusercontent.com/1735941/222610809-ad9112c8-fe9e-409f-b9a4-45159a76ca51.jpeg)

![image](https://user-images.githubusercontent.com/1735941/222610893-36ce2e4c-0c5d-45ee-b493-c95d67a555e1.png)

**Comment by pepsiliu** [comment]
related on #11
