### ISSUE TITLE
FR: Start Print from SD Card

### ISSUE THREAD

**Issue by bjmckenz** [bambulab/Bambu-Handy#74]
I frequently want to start a print when I'm at my phone. Sure, I can't upload an 3MF from my phone :-)

But I have things on my SD card (or even the printer) that i'd like to start -- as if I was doing it from the control panel.

Can has?

Thanks!

**Comment by pepsiliu** [comment]
Yes, it can be implemented. And it also need a supported on the printer first. This feature is in the future feature list.

**Comment by broncosis** [comment]
++  this would be great maybe a small interface to mange the files on the printer too
