### ISSUE TITLE
Android notifications do not honor printer name

### ISSUE THREAD

**Issue by AreYouRlyScared** [bambulab/Bambu-Handy#76]
When receiving a push notification on android the custom printer name is not used, the original printer name is used. 

![Screenshot_20230305_041648_Chrome](https://user-images.githubusercontent.com/1757840/222952598-8b82bcdd-2200-450c-8e3e-e03a1a9f34f3.jpg)

Name in app. 
![Screenshot_20230305_042856_Bambu Handy](https://user-images.githubusercontent.com/1757840/222952602-b5440e80-30be-4519-aee8-659cf36388ec.jpg)

Bambu Handy v1.0.11
Android v13 with Samsung OneUI v5.1
Samsung S23 Ultra

**Comment by pepsiliu** [comment]
Thanks for your report. I have transferred this issue to push-service guys.

**Comment by AreYouRlyScared** [comment]
Its also an issue on iOS, had my friend verify

**Comment by pepsiliu** [comment]
The push-server had supported it.

**Comment by AreYouRlyScared** [comment]
This is still broken and has not been fixed. I am using v1.0.14
