### ISSUE TITLE
Humidity indicator is in the app red

### ISSUE THREAD

**Issue by DokuKaefer** [bambulab/Bambu-Handy#86]
Bambu Lab iPhone Version: 1.0.13

The humidity sensor is displayed in red in the iPhone app.
In the Bambu Studio and on the printer monitor it is green.

![20230331_083856000_iOS](https://user-images.githubusercontent.com/11537653/229071144-f68dbe58-995c-40ca-b412-14f5238944fe.jpg)

![20230331_083910000_iOS](https://user-images.githubusercontent.com/11537653/229071166-21f5c601-70c4-45a0-81d6-ad8f12b32fbc.jpg)

![image](https://user-images.githubusercontent.com/11537653/229071249-54fae93f-c438-4dd1-94ee-0b0cc561b738.png)

![image](https://user-images.githubusercontent.com/11537653/229071322-8bc6e5be-f77d-4be9-877c-98b0de124ac6.png)

**Comment by pepsiliu** [comment]
Yes, A bug on Handy.

**Comment by Filmman586** [comment]
Same

**Comment by Th199403** [comment]
Same

**Comment by brianiup** [comment]
same issue here always red

**Comment by pepsiliu** [comment]
fixed on 1.0.14

**Comment by Th199403** [comment]
@pepsiliu  when is the new app update for ios coming?

**Comment by pepsiliu** [comment]
> @pepsiliu when is the new app update for ios coming?

 The Handy is pending apple and google approval, It'll be available for users after that.
