### ISSUE TITLE
Android Permission Issues

### ISSUE THREAD

**Issue by Podunk209** [bambulab/Bambu-Handy#9]
When trying to attach a photo or video in the ticket submission section I get "Need permission to access your photos" error message, even though permissions are set.  Tried deleting storage and cache and re-installing app and still not working.  Version 1.0.5 on Pixel 6 with Android 13.

**Comment by pepsiliu** [comment]
> When trying to attach a photo or video in the ticket submission section I get "Need permission to access your photos" error message, even though permissions are set. Tried deleting storage and cache and re-installing app and still not working. Version 1.0.5 on Pixel 6 with Android 13.

I have tested on Handy (1.0.5), it works fine for me. Maybe u didn't allow handy to access 'Files and media' permission.

**Comment by Podunk209** [comment]
I'm running 1.0.5 as well.  Under App permissions I don't see an option to allow 'Files and media'  I've allowed every requested permission and show no permissions under "Not allowed" (see screenshot).
![image000000](https://user-images.githubusercontent.com/114607956/195143260-30782f75-f008-45ab-8c30-60bac09f3f48.png)

**Comment by pepsiliu** [comment]
Handy permission check fail because It didn't adapt storage permission on Android 13. It will be fixed on next release version.

**Comment by pepsiliu** [comment]
View on version 1.0.6
