### ISSUE TITLE
[Feature Request] Starting Prints from the app

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/Bambu-Handy#92]
I think it would be handy if you could start prints from the app like if they are saved into the cloud and you want to start a print job you dont have to start the pc just to do so or even if you are away.

**Comment by broncosis** [comment]
agreed or start them from the SD card

**Comment by pepsiliu** [comment]
It's on the future feature list.

**Comment by LibaoBambu** [comment]
Feature has been supported.
