### ISSUE TITLE
[Issue] Infinate App Loading/Connecting to printer. requiring sign out and sign in every timr

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/Bambu-Handy#94]
When opening app, printer view is not available and will be on loading screen continuously. i have to go yo settings, sign out, then sign back in yo gain functionality of the app and interact with the printer

**Comment by pepsiliu** [comment]
@BambuLabDiscord Does it show the loading widget every time?

**Comment by sam43434** [comment]
having the same issue

**Comment by pepsiliu** [comment]
> having the same issue

Could u provide your account email and the time range when the issue occurs.

**Comment by Blair1999** [comment]
Having the same issue here. Any time of day.

**Comment by pepsiliu** [comment]
This issue will be fixed on next released version.

**Comment by Blair1999** [comment]
> This issue will be fixed on next released version.

Awesome, thanks!

**Comment by sam43434** [comment]
> This issue will be fixed on next released version.

is there any time frame for the next release, or just pending apple/ google approval

**Comment by pepsiliu** [comment]
> > This issue will be fixed on next released version.
> 
> is there any time frame for the next release, or just pending apple/ google approval

A new version will be released as soon as this week

**Comment by pepsiliu** [comment]
fixed on 1.0.14
