### ISSUE TITLE
Only german language on v1.1.0

### ISSUE THREAD

**Issue by mainmind83** [bambulab/Bambu-Handy#98]
On update to v1.1.0 only show german language
Uninstall and re-install (clear data and cache) with same result
Spanish language not showed...

![Screenshot_20230512_150402_Bambu Handy](https://github.com/bambulab/Bambu-Handy/assets/18678468/55c59be3-f20e-4e7a-a346-8c589aaf558d)

**Comment by BastR** [comment]
Same for French users, the app only show German.

When you go to “Me - Settings - Language”:

![IMG_7739](https://github.com/bambulab/Bambu-Handy/assets/20129420/cccdc8cc-5a04-491c-bbfd-3cc7ec79373f)

**Comment by mainmind83** [comment]
V1.1.1

`This is a hotfix version. And it just fix the issue that the default language setting.
`

![Screenshot_20230516_220238_Google Play Store](https://github.com/bambulab/Bambu-Handy/assets/18678468/2219e404-1567-4788-a4ae-abecffd1c82a)

**Comment by BastR** [comment]
For me the issues is not fixed, there no French nor Spanish

**Comment by mainmind83** [comment]
@LibaoBambu can you review this bug? Regards

**Comment by LibaoBambu** [comment]
@mainmind83 new version 1.1.1 has beed released in store.

**Comment by BastR** [comment]
Sorry to insist by v1.1.1 doesn’t solve the problem, some languages are missing:


https://github.com/bambulab/Bambu-Handy/assets/20129420/73279e23-0a33-4221-bf45-fb1563343744

**Comment by LibaoBambu** [comment]
The other language translators are still working on it and will be released soon
