### ISSUE TITLE
QR scanner not working

### ISSUE THREAD

**Issue by jps6882** [bambulab/Bambu-Handy#99]
I have tried on two phones and my tablet, and none of them seem to be able to read the QR codes from the printer.  I have no issues with scanning other codes, but the ones for my printer will not work.  I have even tried taking a picture of the code and scanning that while bracing the camera so it doesn't shake in my hands, and they will still not scan.

**Comment by LibaoBambu** [comment]
Can you provide in which scene the QR code is displayed on the printer?  include the model and system version of your phone.

**Comment by LibaoBambu** [comment]
Please reopen if this issue shows up again.
